name: CI Script to build on self-hosted server

on: push

jobs:
  build:
    runs-on: self-hosted
    if: github.repository == 'yacy/yacy_search_server'
    steps:
    - uses: actions/checkout@master
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build linux release
      run: ant clean all dist

